[package]
name = "rohanasan"
version = "0.1.0"
edition = "2021"
publish=true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
async-std = "1.12.0"
